// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDctRyIIPNgGE8IDxgZolyki_9wGrBm-J0',
    appId: '1:943541700401:web:50f2ac3696ea2bbfd25210',
    messagingSenderId: '943541700401',
    projectId: 'arpon-app',
    authDomain: 'arpon-app.firebaseapp.com',
    databaseURL: 'https://arpon-app-default-rtdb.firebaseio.com',
    storageBucket: 'arpon-app.appspot.com',
    measurementId: 'G-EB40LH3JG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HJYT4cC79BdSPy--27waFwLsGRrUtio',
    appId: '1:943541700401:android:c11657cb01de8e11d25210',
    messagingSenderId: '943541700401',
    projectId: 'arpon-app',
    databaseURL: 'https://arpon-app-default-rtdb.firebaseio.com',
    storageBucket: 'arpon-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoMXUVz45Dz8S4sJOtIOH6z7Lt2IwpayA',
    appId: '1:943541700401:ios:4373de05bb86ff0cd25210',
    messagingSenderId: '943541700401',
    projectId: 'arpon-app',
    databaseURL: 'https://arpon-app-default-rtdb.firebaseio.com',
    storageBucket: 'arpon-app.appspot.com',
    androidClientId: '943541700401-1uit4l74m4eeevk68l09rnmk32u0b8hl.apps.googleusercontent.com',
    iosClientId: '943541700401-adfouhbkujsonf7vc2mtosejgblfh5q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoMXUVz45Dz8S4sJOtIOH6z7Lt2IwpayA',
    appId: '1:943541700401:ios:4373de05bb86ff0cd25210',
    messagingSenderId: '943541700401',
    projectId: 'arpon-app',
    databaseURL: 'https://arpon-app-default-rtdb.firebaseio.com',
    storageBucket: 'arpon-app.appspot.com',
    androidClientId: '943541700401-1uit4l74m4eeevk68l09rnmk32u0b8hl.apps.googleusercontent.com',
    iosClientId: '943541700401-adfouhbkujsonf7vc2mtosejgblfh5q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiTest',
  );
}
